# Uncomment this line to define a global platform for your project
# platform :ios, ’10.0’

target 'ILEX' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'SwiftyJSON'
    pod 'Cartography'
    pod 'SwiftyUserDefaults'
    pod 'KeychainAccess'
    pod 'MBProgressHUD'
end
