# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ILEX' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ILEX
     pod 'Alamofire', '~> 4.0'
     pod 'SwiftyUserDefaults'
     pod 'KeychainAccess'
     pod 'SDWebImage/WebP'
end
